name: Test

on:
  pull_request:
    branches:
      - "**"

  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Setup Node lts/gallium
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/gallium'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm test:ci
